name: System Test

on: [push]

jobs:
  system-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Docker Compose
        working-directory: .
        run: docker-compose up -d --build

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - run: pip install pytest requests

      - name: Run system tests
        working-directory: .
        run: pytest

      - name: Bring server down
        working-directory: .
        run: docker-compose down